@startuml
package fig-a {
    a1 . a2
    a1 . a3
    a2 .. a3
}
package fig-b {
    b1 .. b3
    b3 .. b4
    b2 .. b4
    b1 .. b2
    b2 . b3
    b3 . b5
    b6 . b7
}
title 原則\n・図書館を建てるコスト < 道路を作るコスト だったら全ての町に図書館を建てればいい。\n・道路でつながっている町どうしは、図書館1件と道路を（町の数 - 1）本作ればいい。
@enduml