@startuml

(*) --> "get coin"
--> "isSet = False"
--> "get change"
if "dict[change] < 0" then
--> [yes] "get coin"
else
    --> "add coinList"
    if "coin >= change" then
        [yes]if "dict[change] > 0" then
            --> [yes] "ret += dict[change]"
            --> "coinList.pop(-1)"
            --> "get coin"
        else
            --> [no] "isSet = True"
            -->"exec\nsplitCoins(change)"
        endif
    else
        --> [no] "exec\nsplitCoins(change)"
    endif
    --> "coinList.pop()"
    --> "ret += splitCoins(change)"
    if "splitCoins(change) == 0" then
        --> [yes]"dict[change] = -1"
        --> "get coin"
    else
        [no] if "isSet" then
                -->[yes] "dict[change] = ret"
                --> "get coin"
            else
                --> [no]"get coin"
            endif
    endif
endif
@enduml